name: 'Go lang pipeline'
description: 'Go Lang Docker Build, AWS ECR Push and Kustomize step'
inputs:
  go-version:
    description: 'Go lang version'
    required: true
    default: 1.16
  application-name:
    description: 'The application name'
    required: true
  role-to-assume:
    description: 'The AWS OICD role to assume'
    required: true
  role-session-name:
    description: 'The AWS Session name'
    required: true

runs:
  using: "composite"
  steps:
    - run: echo Starting the pipeline
      shell: bash

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ inputs.go-version }}

    - name: Configure AWS credentials from AWS account
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.aws-region }}
        role-session-name: ${{ inputs.role-session-name }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        mask-password: 'true'

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: ${{ inputs.application-name }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG