name: 'Go lang pipeline'
description: 'Go Lang Docker Build, AWS ECR Push and Kustomize step'
inputs:
  app-name:
    description: 'The app name'
    required: true
  aws-region:
    description: 'AWS region name to assume role'
    required: true
  github-deploy-ssh-key:
    description: 'The github deploy SSH key to clone K8S manifests'
    required: true
  github-token:
    description: 'The github token to create PR'
    required: true
  go-version:
    description: 'Go lang version'
    required: true
    default: 1.16
  k8s-manifest-repo-name:
    description: 'The name of K8S manifests repository'
    required: true
  k8s-manifest-repo-ssh:
    description: 'The SSH of K8S manifests repository'
    required: true
  role-session-name:
    description: 'The AWS Session name'
    required: true
  role-to-assume:
    description: 'The AWS OICD role to assume'
    required: true

runs:
  using: "composite"
  steps:
    - name: Get git repository informations
      uses: GFerr3ira/github-actions-git-informations@master

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ inputs.go-version }}

    - name: Configure AWS credentials from AWS account
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.aws-region }}
        role-session-name: ${{ inputs.role-session-name }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        mask-password: 'true'

    - name: Build, tag, and push docker image to Amazon ECR
      shell: bash
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: ${{ inputs.app-name }}
        IMAGE_TAG: ${{ env.RELEASE_VERSION }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    - name: Kustomize step
      uses: GFerr3ira/github-actions-kustomize-argocd-manifests@master
      with:
        app-name: ${{ inputs.app-name }}
        app-registry: ${{ steps.login-ecr.outputs.registry }}
        github-actor: ${{ github.actor }}
        github-deploy-ssh-key: '${{ inputs.github-deploy-ssh-key }}'
        github-token: '${{ inputs.github-token }}'
        k8s-manifest-repo-name: '${{ inputs.k8s-manifest-repo-name }}'
        k8s-manifest-repo-ssh: '${{ inputs.k8s-manifest-repo-ssh }}'